version: '3'
services:
  mysql:
    image: mysql:latest
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --sql_mode="NO_ENGINE_SUBSTITUTION" --explicit_defaults_for_timestamp="ON"
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_USER: root
      MYSQL_PASSWORD:
      MYSQL_DATABASE: blog
